// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWwiiWty-7TgWVej5QWUYjs_cjptwMHTY',
    appId: '1:303597066006:web:913d1b4df921890113a237',
    messagingSenderId: '303597066006',
    projectId: 'authexample1-5e207',
    authDomain: 'authexample1-5e207.firebaseapp.com',
    storageBucket: 'authexample1-5e207.firebasestorage.app',
    measurementId: 'G-PLK9381R44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs4kcqXJ0b5IPfV3nBIF51APyWyrbdBaw',
    appId: '1:303597066006:android:d1947c4f4fe91c1d13a237',
    messagingSenderId: '303597066006',
    projectId: 'authexample1-5e207',
    storageBucket: 'authexample1-5e207.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPPSjiFvnMTSTtVJTm5c8llXyJB6PHt1Q',
    appId: '1:303597066006:ios:e1a06551711a4a7713a237',
    messagingSenderId: '303597066006',
    projectId: 'authexample1-5e207',
    storageBucket: 'authexample1-5e207.firebasestorage.app',
    iosClientId: '303597066006-bj3kus62ds66f6n4dusb8nbkcrgrtm5m.apps.googleusercontent.com',
    iosBundleId: 'com.example.authexample1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPPSjiFvnMTSTtVJTm5c8llXyJB6PHt1Q',
    appId: '1:303597066006:ios:e1a06551711a4a7713a237',
    messagingSenderId: '303597066006',
    projectId: 'authexample1-5e207',
    storageBucket: 'authexample1-5e207.firebasestorage.app',
    iosClientId: '303597066006-bj3kus62ds66f6n4dusb8nbkcrgrtm5m.apps.googleusercontent.com',
    iosBundleId: 'com.example.authexample1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWwiiWty-7TgWVej5QWUYjs_cjptwMHTY',
    appId: '1:303597066006:web:8620181ffdf9ff0213a237',
    messagingSenderId: '303597066006',
    projectId: 'authexample1-5e207',
    authDomain: 'authexample1-5e207.firebaseapp.com',
    storageBucket: 'authexample1-5e207.firebasestorage.app',
    measurementId: 'G-SFRJE5EZQ6',
  );
}
